// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Fallback values ensure the app works even if .env is not present during deploy
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://dclhxbldcslkcnzrtjca.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjbGh4YmxkY3Nsa2NuenJ0amNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0ODAzNDQsImV4cCI6MjA4NzA1NjM0NH0.9tQDVsv9ZmNUTXNr3ufIOIs3k1mY1fFrXVz60iX0LUc';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});